version: '3.9'

services:
  # MongoDB service
  mongo_db:
    container_name: db_container
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    ports:
      - 27017:27017
    volumes:
      - mongo_data:/data/db
  # nodeJs api
  api:
    build: .
    ports:
      - 4000:3000
    environment:
      PORT: 3000
      MONGODB_URI: mongodb://root:password@mongo_db:27017/test

volumes:
  mongo_data: {}
