version: '3.9'

services:
  # MongoDB service
  mongo:
    container_name: db_container
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    ports:
      - 27017:27017
    volumes:
      - mongo_data:/data/db
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    networks:
      my_network:
  # nodeJs api
  api:
    build: .
    ports:
      - 4000:3000
    environment:
      PORT: 3000
      DB_NAME: test
      DB_USER: root
      DB_PASS: password
      MONGODB_URL: mongodb://root:password@mongo:27017/test
    networks:
      my_network:

volumes:
  mongo_data: {}

networks:
  my_network:
