name: hello-world
on: 
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - name: my-step
        run: 'echo "$DOCKERHUB_USERNAME" > key'
        shell: bash
        env:
          DOCKERHUB_USERNAME: ${{secrets.DOCKERHUB_USERNAME}}
      - uses: actions/checkout@v4
      - name: docker login
        env:
          DOCKERHUB_USERNAME: ${{secrets.DOCKERHUB_USERNAME}}
          DOCKERHUB_TOKEN: ${{secrets.DOCKERHUB_TOKEN}}
        run: |
          docker login -u $DOCKERHUB_USERNAME -p $DOCKERHUB_TOKEN
      - name: Build the docker image
        run: docker build . --file Dockerfile --tag abdur890000/nodejswithmongodb:$(date+%s)

      - name: Docker Push
        run: docker push ${{secrets.DOCKERHUB_USERNAME}}/nodejswithmongodb
